vocabs:
  SNOMED:
    licensed: false
    territory: US
  MedDRA:
    licensed: true
    territory: US
  LOINC:
    licensed: true
  RxNorm:
    licensed: true
  HPO:
    licensed: true
actions:
  redact_unlicensed_codes: true  # Guards downstream processors from leaking restricted terminology.
  block_kg_write_without_provenance: true
  fail_on_unlicensed_usage: true
