name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          environment-name: ci
          cache-downloads: true
          cache-env: true
      - name: Run tests with coverage
        shell: bash -l {0}
        run: |
          python -V
          pytest
      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          if-no-files-found: warn
          path: |
            coverage.xml
            htmlcov/
