name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          environment-name: ci
          cache-downloads: true
          cache-env: true
      - name: Type check core services
        shell: bash -l {0}
        run: |
          python -m mypy --strict \
            src/Medical_KG/config \
            src/Medical_KG/utils/optional_dependencies.py \
            src/Medical_KG/cli.py
      - name: Check for legacy ingestion commands
        shell: bash -l {0}
        continue-on-error: true
        run: |
          python scripts/cli_migration/check_ci_commands.py
      - name: Run tests
        shell: bash -l {0}
        run: |
          python -V
          pytest -q
